// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solution.Persistence;

namespace Solution.Persistence.Migrations
{
    [DbContext(typeof(SolutionDbContext))]
    partial class SolutionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Solution.Domain.Curso", b =>
                {
                    b.Property<Guid>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = new Guid("a9a1cec6-a6a5-419f-916c-ff81ba940e80"),
                            Descripcion = "Curso de C# basico",
                            FechaCreacion = new DateTime(2025, 4, 24, 17, 38, 57, 766, DateTimeKind.Local).AddTicks(9209),
                            FechaPublicacion = new DateTime(2026, 4, 24, 17, 38, 57, 768, DateTimeKind.Local).AddTicks(4057),
                            Precio = 56m,
                            Titulo = "C# desde 0 hasta avanzado"
                        },
                        new
                        {
                            CursoId = new Guid("60b9e0b2-97b5-4a2c-95c6-ad32c9517bfc"),
                            Descripcion = "Curso de Javascript",
                            FechaCreacion = new DateTime(2025, 4, 24, 17, 38, 57, 769, DateTimeKind.Local).AddTicks(2256),
                            FechaPublicacion = new DateTime(2026, 4, 24, 17, 38, 57, 769, DateTimeKind.Local).AddTicks(2260),
                            Precio = 30m,
                            Titulo = "Javascript desde 0 hasta avanzado"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
